[project]
name = "rl-map-navigation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "PyQt6>=6.10.1",
    "torch>=2.9.1",
    "numpy>=2.4.0"
]
